services:
  postgres:
    image: postgres:18-alpine
    container_name: crave_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crave_db
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crave-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Zookeeper service REMOVED (Not needed for KRaft)

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: crave_kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRaft Configuration ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # --- General Settings ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # A static Cluster ID is required for KRaft. We generate a random one here.
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    # This command formats the storage with the Cluster ID before starting the server
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"kafka-storage format --ignore-formatted -t $CLUSTER_ID -c /etc/kafka/kafka.properties\" >> /tmp/update_run.sh && echo \"/etc/confluent/docker/run\" >> /tmp/update_run.sh && chmod +x /tmp/update_run.sh; fi && /tmp/update_run.sh'"
    networks:
      - crave-network

  localstack:
    image: localstack/localstack:4.9.0
    container_name: crave_localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack_data:/var/lib/localstack"
    networks:
      - crave-network

networks:
  crave-network:
    driver: bridge